#
# This devcontainer will create a bare bones container with the astral-sh-uv Python package installed.
#
# Afterwards, use uv commands to create the Python environment
version: '3.8'

services:
  devcontainer:
    image: astral-sh-uv:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/workspace:cached
    command: /bin/sh -c "while sleep 1000; do :; done"

